### ISSUE TITLE
Multiline string highlighting

### ISSUE THREAD

**Issue by pylipp** [peterhoeg/vim-qml#13]
The following snippet
```
import QtQuick.Controls 2.2

TextArea {
    text: "This is the first line.
This: is the second.
And we have a third one, too."
}
```
is highlighted like this:
![image](https://user-images.githubusercontent.com/10617122/42570943-d42126b4-8515-11e8-8922-fcd2100c1950.png)

It would be more consistent to have the second and third line of the string highlighted in 'String' color as well. Is this possible? Or should I use a different approach to put multiline strings?

**Comment by peterhoeg** [comment]
It definitely would be more consistent. Are you interested in putting together a PR?
