### ISSUE TITLE
Upstreaming?

### ISSUE THREAD

**Issue by ubitux** [peterhoeg/vim-qml#24]
It looks like this code is relatively stable: any reason not to submit it upstream to vim?

**Comment by vimpostor** [comment]
With https://github.com/vim/vim/issues/12806 upstreamed this issue can probably be closed and there should probably be a note in the README that vim now has QML support by default.

**Comment by peterhoeg** [comment]
vim has support with https://github.com/vim/vim/pull/12810 merged, yes, but we're still waiting for neovim.

**Comment by vimpostor** [comment]
Neovim now also has support with https://github.com/neovim/neovim/pull/24812

**Comment by peterhoeg** [comment]
Indeed, thank you bringing it up.
