### ISSUE TITLE
dose anyone know how to generite qml ctags?

### ISSUE THREAD

**Issue by nocanstillbb** [peterhoeg/vim-qml#27]

**Comment by peterhoeg** [comment]
I'm not sure exactly what you are looking to do. Can you elaborate?

**Comment by nocanstillbb** [comment]
> I'm not sure exactly what you are looking to do. Can you elaborate?
I want to use the tag function in vim to automatically complete qml code and find qml symbols, ctrl-] ctrl-t

**Comment by peterhoeg** [comment]
That will be handled via QML support in the Qt language server: https://bugreports.qt.io/browse/QTBUG-102038

**Comment by peterhoeg** [comment]
There is also this: https://invent.kde.org/sdk/qml-lsp

**Comment by nocanstillbb** [comment]
ok thanks for your answer
