### ISSUE TITLE
First return operand isn't highlighted in js ternary expressions

### ISSUE THREAD

**Issue by ryanneph** [peterhoeg/vim-qml#9]
Consider the snippet:
```qml
FileDialog {
  property string intent: "load"
  function isLoad() { return (intent=="load"); }
  title: isLoad() ? "Select a file to load" : "Select a location to save the file"
                    -----------------------   ------------------------------------
                       not highlighted               properly highlighted
  ...
}
```
We see that the first of the two return operands in the ternary expression is not highlighted as a string as it should be; though the second string is properly highlighted.
![2017-11-02-17 55 22_768x230_scrot](https://user-images.githubusercontent.com/9826865/32357124-0b1cfa56-bff7-11e7-91b2-e441bde90a63.png)

This seems to occur regardless of the type of the first return operand. 
![2017-11-02-18 00 35_418x22_scrot](https://user-images.githubusercontent.com/9826865/32357194-bf9dcb36-bff7-11e7-8ea9-67b990236fbd.png)

Sorry to bother. I'll take a crack at correcting this over the weekend and follow up with a PR.

**Comment by peterhoeg** [comment]
Thanks for reporting this. A PR would be *most* welcome!
